### PR TITLE
Make the password parameter optional

### PR DESCRIPTION
**Pull request by rnelson0**

### CODE REVIEW

**Comment by rnelson0** [comment]
Fixes #64

**Comment by rnelson0** [comment]
I can only guarantee that this allows the user to skip providing the password. Someone who uses the module will have to try it to ensure the two powershell scripts work properly when provided with a password of `""` (empty string).

**Comment by natemccurdy** [comment]
@rnelson0 Thanks for making this!

Quick clarification, your patch will allow a password of either a String[1] or undef, not the empty string. But that should be fine.... assuming the PowerShell scripts can handle that (a quick look makes me think they can).

With your patch, this should be possible now  (note the lack of a password):

```puppet
sslcertificate { "Install-PFX-Certificate" :
  name       => 'mycert.pfx',
  location   => 'C:\',
  thumbprint => '07E5C1AF7F5223CB975CC29B5455642F5570798B'
}
```

But this will still throw an error (which is fine if the above works):

```puppet
sslcertificate { "Install-PFX-Certificate" :
  name       => 'mycert.pfx',
  password   => '',
  location   => 'C:\',
  thumbprint => '07E5C1AF7F5223CB975CC29B5455642F5570798B'
}
```

**Comment by rnelson0** [comment]
@natemccurdy I was referring to the underlying powershell script's cmdlet receiving `""` in the password argument when `$password = undef`. To use an actual password should definitely require a non-null string.

**Pull request merged**
